[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = 'elm'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # scala syntax
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]] # python syntax and antocompletion
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]] # rust syntax
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]] # color scheme
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'kana/vim-submode'

# file browser NERDTreeToggle
[[plugins]]
repo = 'scrooloose/nerdtree'

# taglist.vim
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# caw.vim comment out toggle short cut
[[plugins]]
repo = 'tyru/caw.vim'
